### ISSUE TITLE
LoadError: no such file to load -- maven/ruby/maven

### ISSUE THREAD

**Issue by kares** [mkristian/jar-dependencies#19]
trying to `resolve_dependencies`

```
Fetching: ruby-maven-libs-3.1.1.gem (100%)
Fetching: descendants_tracker-0.0.4.gem (100%)
Fetching: ice_nine-0.11.1.gem (100%)
Fetching: axiom-types-0.1.1.gem (100%)
Fetching: coercible-1.0.0.gem (100%)
Fetching: equalizer-0.0.11.gem (100%)
Fetching: virtus-1.0.5.gem (100%)
Fetching: maven-tools-1.0.8.gem (100%)
Fetching: ruby-maven-3.1.1.0.11.gem (100%)
rake aborted!
LoadError: no such file to load -- maven/ruby/maven
/opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/jar-dependencies-0.1.12/lib/jars/maven_exec.rb:116:in `lazy_load_maven'
/opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/jar-dependencies-0.1.12/lib/jars/maven_exec.rb:73:in `do_resolve_dependencies'
/opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/jar-dependencies-0.1.12/lib/jars/maven_exec.rb:63:in `resolve_dependencies_list'
/opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/jar-dependencies-0.1.12/lib/jars/classpath.rb:40:in `resolve_dependencies'
```

**Comment by mkristian** [comment]
this is strange: https://github.com/mkristian/jar-dependencies/blob/master/lib/jars/maven_exec.rb#L116 is followed by a ```rescue LoadError``` so in this case it should install ruby-maven and then use it. the output suggests that ruby-maven got installed.

and there is a test which tries to test this lazy_load_maven as well.

I guess I need to try it with RVM

**Comment by kares** [comment]
on a second thought, I think it simply won't work when Bundler is loaded since it patched RubyGems to act with LoadErrors such as the above for gems that are not in the Bundle ... it is quite an annoying "feature" ;(

**Comment by mkristian** [comment]
OK, it is together with bundler. let me see, this can be fixed

**Comment by mkristian** [comment]
@kares if you could try a local build of the gem - that would be great.

**Comment by kares** [comment]
thanks, will sure try but I'm afraid Bundler is doing a good job preventing us from loading any gem outside the bundle these days ;( ... as it likely patches gem activation (as well). there's nothing more to be done here - changes look great and thanks for adding me among the repository's contributors!
