### ISSUE TITLE
vendoring your jars before packing the jar instructions errors out

### ISSUE THREAD

**Issue by joekiller** [mkristian/jar-dependencies#35]
I was trying to make a rake task per the instructions here: https://github.com/mkristian/jar-dependencies#vendoring-your-jars-before-packing-the-jar however I get a wrong number of arguements calling error.

```
  1) Error:
Jars::Installer#test_0008_tests default vendor_jars task:
ArgumentError: wrong number of arguments calling `vendor_jars` (0 for 2)
    /home/jlawson/public/jar-dependencies/specs/jar_installer_spec.rb:118:in `test_0008_tests default vendor_jars task'
```

I created PR #34 to exercise the issue.

**Comment by joekiller** [comment]
Is `Jars::JarInstaller.vendor_jars` supposed to be ` Jars::JarInstaller.install_jars`?

**Comment by mkristian** [comment]
```
Jars.lock_down(false, false, :vendor_dir => 'lib')
```
will vendor the jars into the lib directory. I am about to push a shortcut for this and see to fix the README - though for the README I would need to release a new gem

**Comment by mkristian** [comment]
@joekiller fixed the readme - thanx for reporting
