### ISSUE TITLE
Example to add custom repo to gemspec?

### ISSUE THREAD

**Issue by joekiller** [mkristian/jar-dependencies#37]
#8 mentions new DSL that allows you to "declare a repo inside the gemspec". Could I get an example of this?

**Comment by mkristian** [comment]
no there is no way to do this beside setting up a settings.xml and tell jruby via environment ```MAVEN_SETTINGS``` where this settings.xml is located.

**Comment by joekiller** [comment]
Okay thanks! I was chuckling to myself because I was working on some
logstash stuff and reading the old issues it looks like logstash guys love
asking this question.
