### ISSUE TITLE
lib/my_gem_jars.rb not created when jar-dependencies is a development dependency

### ISSUE THREAD

**Issue by joekiller** [mkristian/jar-dependencies#38]
The following command to version the jars and make the my_gem_jars.rb file doesn't work if jar-dependencies is declared `add_development_dependency`.

```ruby
require 'jars/installer'
task :install_jars do
  Jars::Installer.new.vendor_jars
end
```

Even if I do `Jars::Installer.new.vendor_jars true` it doesn't work because `has_jars?` returns false because the dependency type isn't runtime (https://github.com/mkristian/jar-dependencies/blob/f6b3c202e3178dde6223a079e30cd7e4b916bca5/lib/jars/installer.rb#L177):

```ruby
        spec.dependencies.detect { |d| d.name == 'jar-dependencies' && d.type == :runtime } != nil
```

So I think right now, I have to make jar-dependencies runtime and get the file and then I can get the jar file and continue. Just a pain to have to change it back and forth.

**Comment by mkristian** [comment]
looking at this now

**Comment by mkristian** [comment]
@joekiller is there a way of testing this patch for me ? as I do not find time for a proper testcase right now

**Comment by joekiller** [comment]
You can update jruby-kafka use jar-dependencies as a development dep and
run then make the rake task in
https://github.com/joekiller/jruby-kafka/blob/master/Rakefile

If you don't have time I'll probably try it Monday.
