### ISSUE TITLE
Jruby on Rails Setup with jar dependency management

### ISSUE THREAD

**Issue by rawandrew** [mkristian/jar-dependencies#41]
Hi Christian,

I am trying to get a JRuby on Rails project going and it will rely heavily on Java jars. What would be the best way to manage those jar dependencies so that they also get bundles into the final war file?

If you could point me to an example setup or some sort of updated documentation I would be really grateful.

Thank you.

**Comment by kares** [comment]
Bundler + JBundler should work reasonably - Warbler has support for JBundler.
some things need to be figured out -> `require 'jbundler' unless $servlet_context` probably :)
