### ISSUE TITLE
[question] Set jars and #{spec.name}_jars.rb root path ?

### ISSUE THREAD

**Issue by ebuildy** [mkristian/jar-dependencies#44]
Sorry to post it here,

From here: https://github.com/mkristian/jar-dependencies/blob/master/lib/jars/installer.rb#L199, it seems not possible to set the root path when calling ``Jars::Installer.vendor_jars!``?

Thanks,

**Comment by mkristian** [comment]
@ebuildy so you want to have ```Jars::Installer.vendor_jars!(some_dir)``` ? currently it uses the required_path of the gemspec.

**Comment by ebuildy** [comment]
Yes i would like  specify this, Logstash team asked me to put  vendor files
outside lib directory.

Is that possible ?

Thanks,
Le 14 avr. 2016 08:28, "Christian Meier" <notifications@github.com> a
écrit :

**Comment by mkristian** [comment]
if you put the vendored jars outside of the lib directory lets say ./vendor/jars then you need to add this vendor/jars directory to the $LOAD_PATH for ```require_jar(...)``` to find them. or add vendor/jars to you require_paths of you gemspec (where rubygems itself add the path to the $LOAD_PATH).

yes can be done and I have to double check the ```gemspec#require_paths```.

**Comment by ebuildy** [comment]
You think it's a bad idea?

Also, what is the best moment to run this, at dev. time (means add *.jars in git repository), or at run time?

Thanks you,

**Comment by mkristian** [comment]
@ebuildy to add the vendor jars somewhere else is OK. I will find some time for implementing it soon.

the time of vendoring is when you build the gem IMO, i.e. not putting them into the git repo.

**Comment by ebuildy** [comment]
Thanks you again,

Why running ``bundle install`` installs also jar dependencies? I don't find documentation about it.

**Comment by mkristian** [comment]
https://github.com/jruby/jruby/blob/master/lib/ruby/stdlib/rubygems/defaults/jruby.rb#L123
https://github.com/mkristian/jar-dependencies/blob/master/lib/rubygems_plugin.rb#L21

both setup a post_install hook for rubygems, i.e. whenever some gem gets installed the registered post_install_hook will install the jars, if 'jar-dependencies' is a runtime dependency and the platform is 'java' of the gem.

if you vendor jars you should use development dependency for jar-dependencies but has the disadvantage that it works only with jruby-1.7.20+ and jruby-9k

**Comment by ebuildy** [comment]
Ho! Ok I start to understand what happen ;-) 

So running ``gem install XXX`` will install jars from final user machine?

**Comment by mkristian** [comment]
it will trigger https://github.com/mkristian/jar-dependencies/blob/master/lib/jars/installer.rb#L150
and if gem is platform java and jar-dependencies is a runtime dependency then the jars will be vendored. and in this case you do not need to pack any jars inside the gem, as packed jars will be ignored.

**Comment by ebuildy** [comment]
In generated ``#{spec.name}_jars.rb`` file:

````
require 'jar_dependencies'
require_jar( 'eu.bitwalker', 'UserAgentUtils', '1.19' )
````

 jar-dependencies seems required at runtime also?

**Comment by mkristian** [comment]
that can be made failsafe - will add this as well.

**Comment by mkristian** [comment]
the generated file will now work with older jrubies d896d4f983547b08cc0d0acf7da670e0d209dd34

**Comment by suyograo** [comment]
@mkristian thanks for this fix.. any idea when you would be releasing a version with this fix in?

**Comment by mkristian** [comment]
wanted to get travis green which would need a new polyglot-maven release,
which I am got an OK to go yesterday. probably over the weekend everything
gets released.

**Comment by mkristian** [comment]
@suyograo just released another bug-fix release including the patched for this issue
