### ISSUE TITLE
Question: Jackson jar loading wrt JrJackson and Logstash Java Event.

### ISSUE THREAD

**Issue by guyboertje** [mkristian/jar-dependencies#45]
We see this in Logstash:
`--- jar coordinate com.fasterxml.jackson.core:jackson-annotations already loaded with version 2.7.1 - omit version 2.7.0`

Reading the code from this library, I see that it is a warning but I could not figure out how the version resolution worked.
Logstash has a gem dependency on JrJackson and loads before Logstash internals
logstash-core-event-java uses Jackson

Does jar_dependencies use the first declared jar?
Or does it attempt to resolve for the best major/minor/patch?

/cc @colinsurprenant

**Comment by mkristian** [comment]
jar-dependencies just loads the jars whenever the respective require happens. but ensures that if a version of jar is already loaded that it will be the only version of this jar loaded.

in your case com.fasterxml.jackson.core:jackson-annotations:2.7.1 was already loaded and later some require came which wanted to load com.fasterxml.jackson.core:jackson-annotations:2.7.0 which gets ignored.

if you application runs some other execution path the very same application could first load com.fasterxml.jackson.core:jackson-annotations:2.7.0 and then jar-dependencies will ignore the other one with 2.7.1

this is about the same what happens with gems when not using bundler, i.e. a gem gets activated and for some reason the code wants to activate the same gem with another version it bails out.

so jar-dependencies just avoids to get jars loaded with different versions.

to lock the jars you need to create the Jars.lock via `lock_jars`, i.e. the bundler thing for jars.

**Comment by guyboertje** [comment]
Thanks @mkristian
