### ISSUE TITLE
Does jar-dependencies follow semvar?

### ISSUE THREAD

**Issue by dqdinh** [mkristian/jar-dependencies#55]
I notice that different patch versions of jar-dependencies will create errors during development of https://github.com/lookout/fast-rsa-engine

https://github.com/lookout/fast-rsa-engine/pull/27

**Comment by mkristian** [comment]
http://semver.org/#spec-item-4

I would say yes. but what is the actual problem ?

**Comment by mkristian** [comment]
oh I saw your other message

**Comment by dqdinh** [comment]
Thanks for the clarification about major version zero (0.y.z)  in semvar.

**Comment by mkristian** [comment]
@dqdinh I forgot to mention that this break was unintentional, so please file an issue for such a problem here the next time. thanx even for bringing the problem to my attention.

**Comment by mkristian** [comment]
ah - you did :)
