### ISSUE TITLE
scope:provided not respected when installing gems

### ISSUE THREAD

**Issue by dgolombek** [mkristian/jar-dependencies#60]
When installing a gem using jar-dependencies where the gemspec has a jar with :scope => :provided in it's requirements, the jar is downloaded and placed into the gem directory. I believe this is contrary to the meaning of the provided scope and the intentions of the gem. This causes problems when using warbler, since the entire gem directory is then embedded in the war, and for us that leads to having multiple versions of the jar present, with no clean way to avoid it. The gem in question is lookout/fast-rsa-engine, but I don't think this is specific to that gem.

I suspect this is due to a bad symbol vs string comparison at https://github.com/mkristian/jar-dependencies/blob/master/lib/jars/maven_factory.rb#L17 but I've run out of time right now to track that down farther. Hopefully I'll get some more time to work on this soon, if you don't have a chance to.

**Comment by dgolombek** [comment]
Ok, dove in farther and understood more, this isn't a jar-dependencies bug. This gem is indeed ignoring the jars labeled as provided. This appears to be a joint bug in the fast-rsa-engine gem and how jruby maven plugins parse the gemspec. I'll follow up there. Sorry about the trail of bad bug reports, still learning how this toolchain works :-(

**Comment by mkristian** [comment]
@dgolombek is there an easy way to reproduce the problem ?
