### ISSUE TITLE
Code style enhancement: remove additional whitespace

### ISSUE THREAD

**Issue by paulgoetze** [mkristian/jar-dependencies#63]
Speaking of additional whitespace (#61):

@mkristian, should the recommended Ruby code style regarding whitespace around parentheses (`()`, `[]`) be made consistent throughout the whole project? Meaning: Should additional whitespace be removed?

I just did a quick search and it looks like it would affect more than 1500 locations in 41 Ruby files.
Taking into account that this project is bundled into recent JRuby versions, and therefore heavily used, it might make sense to improve the code quality a bit, starting with these changes. Also, it might be a good point in time, since there is no open PR at the moment, where these changes could introduce merge conflicts.

If you are ok with that, I would prepare a PR that removes all the additional whitespace without changing any functionality or other code style issues.

**Comment by mkristian** [comment]
@paulgoetze yes, sounds like a good idea. I think rubocop can do such changes, if you know how to changes easily then just go ahead.

**Comment by paulgoetze** [comment]
Great. On it.

**Comment by paulgoetze** [comment]
@mkristian I found that running `rubocop --auto-correct` automatically fixes [lots of style issues](https://github.com/bbatsov/rubocop/wiki/Automatic-Corrections#already-support-auto-correct) besides the whitespace inside of parentheses. 

So it will also fix alignments, the Ruby 1.9 style hash key syntax, etc. Will there be any problems with just running the whole auto-correction for simplicity?

I prepared a branch with the Rubocop auto-corrections (`rubocop -a`). You can have a look at the diffs [here](https://github.com/mkristian/jar-dependencies/compare/master...paulgoetze:fix/ruby-code-style?expand=1). For now I disabled adding the frozen string literal comment because it let’s the test fail (given that `String#strip!` is used in the installer).

**Comment by paulgoetze** [comment]
Cool, then I'll open a PR with these changes later today.

Regarding a linting check during Travis runs: I must say I am not really a fan of running linting as a pass criteria in a testing CI. However,  there are nice other services (such as [Codacy](https://www.codacy.com)) to check for code issues and provide you with additional info (also using Rubocop). As far as I can see, you would have to scan through the logs in Travis to see what went wrong. If we want to enforce a certain codestyle I would rather recommend to add a Rubocop config to the project and give some hints in the contribution notes about checking for code style issues. Or even integrate with e.g. Codacy here on Github and enforce positive commits in order to be able to merge a PR. Just my personal opinion. What do you think?

**Comment by mkristian** [comment]
yes, you are right travis is not the right place. seeing Codacy it looks like it has some overlap to CodeClimate. I need to have a look at both of them and see what to pick.

is it hard to add a minimal rubucop config with your PR which goes along with the changes from the PR ? no pressure here ;)

**Comment by paulgoetze** [comment]
:) Sure, I’ll add one.
