### ISSUE TITLE
Jar files dowloaded with size 0

### ISSUE THREAD

**Issue by mlicursi** [mkristian/jar-dependencies#70]
Downloading jar-dependencies as dependency of an other package I noticed that the .jar file under ./specs/deps have size 0.  Is this intentional? What is the  intended method to download full  dependencies locally? Thanks

**Comment by mkristian** [comment]
@mlicursi so all jars under specs/deps are for the tests and I do not need any content in them, so an empty jar will do. they are not part of jar-dependencies dependencies (sorry for the wording), i.e. see jar-dependencies.gemspec: there are no runtime gem dependencies with this gem.

does this answer your question ?

**Comment by mlicursi** [comment]
Yes, this clarifies my doubt.  Thanks a lot for the rapid answer.
