### ISSUE TITLE
Update ruby/maven infrastructure and get integration tests passing

### ISSUE THREAD

**Issue by headius** [mkristian/jar-dependencies#84]
I am attempting to update the ruby/maven infrastructure but running into problems getting everything sorted.

* When the jar-dependencies pom is generated into my local repo, it appears to have a bunch of null characters at the end. Not sure if this is a bug in JRuby or Mavengem or the jruby-maven-plugins.

```
[INFO] [WARNING] The POM for rubygems:jar-dependencies:gem:0.5.0 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model
[INFO] [FATAL] Non-parseable POM /Users/headius/.m2/repository/rubygems/jar-dependencies/0.5.0/jar-dependencies-0.5.0.pom: in epilog non whitespace content is not allowed but got \u0 (position: END_TAG seen ...</build>\n</project>\n\u0... @85:2)  @ line 85, column 2
```

* Somehow it still complains about the missing torquebox proxy even though I do not have that configured. Perhaps picking up from some other gem?

```
[INFO] [INFO] Downloading from mavengems: mavengem:https://rubygems.org/rubygems/adamantium/maven-metadata.xml
[INFO] [INFO] Downloading from central: https://repo.maven.apache.org/maven2/rubygems/adamantium/maven-metadata.xml
[INFO] [INFO] Downloaded from mavengems: mavengem:https://rubygems.org/rubygems/adamantium/maven-metadata.xml (604 B at 25 kB/s)
[INFO] [WARNING] Could not transfer metadata rubygems:adamantium/maven-metadata.xml from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [rubygems-prereleases (http://rubygems-proxy.torquebox.org/prereleases, default, snapshots)]
```

* Activating the new jar-dependencies when using JRuby 9.4.8.0 for Ruby stuff causes it to complain and fail (0.4.1 is already activated):

```
[INFO] [INFO] --- exec:3.5.0:exec (default) @ bundle_with_path ---
[INFO] Gem::LoadError: can't activate jar-dependencies-0.5.0, already activated jar-dependencies-0.4.1
[INFO]   check_version_conflict at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:2278
[INFO]                 activate at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:1415
[INFO]                      gem at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_gem.rb:68
[INFO]              synchronize at org/jruby/ext/thread/Mutex.java:171
[INFO]                      gem at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_gem.rb:68
[INFO]                   <main> at bundle.rb:6
[INFO] [ERROR] Command execution failed.
```

Given the many old versions that I'm trying to update (all pushed to master) I don't believe the integration tests were passing before, but I want to get them passing before I release the updated jar-dependencies.

@mkristian I could use your help here... not sure where I am missing configs to get these integration tests working.

**Comment by headius** [comment]
@mkristian Looks like the polyglot jars did not get into the ruby-maven gem... is that something I have to do manually before releasing?

https://github.com/mkristian/jar-dependencies/actions/runs/11581620742/job/32242788552#step:5:22

**Comment by headius** [comment]
I have yanked ruby-maven-3.9.0 for now to avoid users hitting a broken release.

**Comment by mkristian** [comment]
@headius did you use maven to build the gem (and deploy it tu rubygems.org ) ? https://github.com/jruby/ruby-maven?tab=readme-ov-file#building

**Comment by headius** [comment]
@mkristian Yes I believe that I followed the instructions in README.

**Comment by jsvd** [comment]
> @mkristian Looks like the polyglot jars did not get into the ruby-maven gem... is that something I have to do manually before releasing?

Not sure if this helps, but the jar is there (3.9.0.pre1 is the same size as the yanked 3.9.0 - 100kb):

```
❯ gem fetch ruby-maven -v 3.9.0.pre1
Downloaded ruby-maven-3.9.0.pre1

❯ gem unpack ruby-maven-3.9.0.pre1.gem
Unpacked gem: 'ruby-maven-3.9.0.pre1'

❯ find ruby-maven-3.9.0.pre1 -name "*.jar" 
ruby-maven-3.9.0.pre1/lib/extensions/polyglot-ruby-0.7.1.jar
ruby-maven-3.9.0.pre1/lib/extensions/polyglot-common-0.7.1.jar
```

The CI mentions:
> Errno::ENOENT: No such file or directory - /home/runner/work/jar-dependencies/jar-dependencies/vendor/bundle/jruby/3.1.0/gems/ruby-maven-3.9.0/lib/polyglot_jars

So I don't see how the jars can go from `lib/extensions` to `lib/polyglot_jars`. either there's nothing moving them there, or if there's code to do it, it's broken.

**Comment by headius** [comment]
I modified the code accessing `polyglot_jars` to access `extensions` and that appears to fix the issue. @mkristian Perhaps you intended to rename `extensions` but forgot that step?

ruby-maven 3.9.2 is released and seems to work correctly from my simple tests.

I will try to proceed with jar-dependencies update today.

**Comment by mkristian** [comment]
@headius what I did to test this:

installed jruby-9.4.9.0 via rbenv, build the jar-dependencies-0.5.0.gem and replaced the default jar-dependencies-0.4.1 from the jruby install. Then

```
$ rake specs
....
Finished in 84.743536s, 0.7080 runs/s, 8.6850 assertions/s.

60 runs, 736 assertions, 0 failures, 0 errors, 2 skips
```

It just needed 
```
% git diff
diff --git a/specs/classpath_spec.rb b/specs/classpath_spec.rb
index 6f8bd29..8827785 100644
--- a/specs/classpath_spec.rb
+++ b/specs/classpath_spec.rb
@@ -13,7 +13,8 @@ module Helper
       org/jruby/yecht/yecht.jar
     ]
     result = array.collect do |a|
-      a.sub(/-native.jar$/, '.jar')
+      a.sub(/\.jar.*$/, '.jar')
+       .sub(/-native.jar$/, '.jar')
        .sub(/-[^-]+$/, '.jar')
        .sub(%r{[^/]+/([^/]+)$}, '\1')
        .sub(/^.*META-INF.jruby.home.lib.ruby.s....../, '')   
```

**Comment by mkristian** [comment]
I also removed all maven cache ~/.m2 and all works fine.

**Comment by headius** [comment]
I followed your steps and it did indeed build and run specs successfully. I've pushed 0.5.0, so closing this.

**Comment by headius** [comment]
JRuby master (9.4.10.0) has updated jar-dependencies and is passing. I had to push a snapshot of 9.4.10.0 in order for the build to use that as the jruby-jars gem-building runtime, otherwise we'd get two different jar-dependencies activating.

Note that there's still an open challenge here: make it possible to update jar-dependencies independent of JRuby. As it stands today, it's not possible for existing 9.4.9.0 and earlier users to update jar-dependencies via the gem, since it is activated before RubyGems fully loads. That means any accidental install of jar-dependencies 0.5.0 on those versions will potentially break until they remove it again.

See #86.
